USE team05;
DROP TABLE IF EXISTS review;
CREATE TABLE review (
    review_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT(11) NOT NULL,
    rest_id INT(11) NOT NULL,
    content VARCHAR(300),
    rating INT(5),
    FOREIGN KEY(user_id) REFERENCES user(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(rest_id) REFERENCES restaurant(rest_id) ON UPDATE CASCADE ON DELETE CASCADE 
);

INSERT INTO review (user_id, rest_id, content, rating) VALUES (47, 32, "Wow... Loved this place.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (140, 32, "Crust is not good.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (141, 79, "Not tasty and the texture was just nasty.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (114, 55, "Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (115, 66, "The selection on the menu was great and so were the prices.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (97, 91, "Now I am getting angry and I want my damn pho.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (39, 70, "Honeslty it didn't taste THAT fresh.)", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (151, 88, "The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (36, 14, "The fries were great too.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (146, 20, "A great touch.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (131, 30, "Service was very prompt.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (90, 70, "Would not go back.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (99, 87, "The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (32, 41, "I tried the Cape Cod ravoli, chicken, with cranberry...mmmm!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (72, 15, "I was disgusted because I was pretty sure that was human hair.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (70, 9, "I was shocked because no signs indicate cash only.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (55, 47, "Highly recommended.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (126, 57, "Waitress was a little slow in service.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (77, 4, "This place is not worth your time, let alone Vegas.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (57, 56, "did not like at all.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (93, 54, "The Burrittos Blah!", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (149, 55, "The food, amazing.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (92, 44, "Service is also cute.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (127, 47, "I could care less... The interior is just beautiful.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (138, 15, "So they performed.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (82, 29, "That's right....the red velvet cake.....ohhh this stuff is so good.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (68, 37, "- They never brought a salad we asked for.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (22, 47, "This hole in the wall has great Mexican street tacos, and friendly staff.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (48, 54, "Took an hour to get our food only 4 tables in restaurant my food was Luke warm, Our sever was running around like he was totally overwhelmed.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (79, 45, "The worst was the salmon sashimi.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (110, 38, "Also there are combos like a burger, fries, and beer for 23 which is a decent deal.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (47, 47, "This was like the final blow!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (5, 35, "I found this place by accident and I could not be happier.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (132, 74, "seems like a good quick place to grab a bite of some familiar pub food, but do yourself a favor and look elsewhere.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (62, 58, "Overall, I like this place a lot.	", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (18, 57, "The only redeeming quality of the restaurant was that it was very inexpensive.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (151, 51, "Ample portions and good prices.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (84, 47, "Poor service, the waiter made me feel like I was stupid every time he came to the table.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (126, 64, "My first visit to Hiro was a delight!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (16, 44, "Service sucks.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (149, 28, "The shrimp tender and moist.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (11, 17, "There is not a deal good enough that would drag me into that establishment again.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (9, 36, "Hard to judge whether these sides were good because we were grossed out by the melted styrofoam and didn't want to eat it for fear of getting sick.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (92, 42, "On a positive note, our server was very attentive and provided great service.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (134, 68, "Frozen pucks of disgust, with some of the worst people behind the register.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (129, 17, "The only thing I did like was the prime rib and dessert section.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (24, 68, "It's too bad the food is so damn generic.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (46, 22, "The burger is good beef, cooked just right.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (53, 1, "If you want a sandwich just go to any Firehouse!!!!!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (42, 59, "My side Greek salad with the Greek dressing was so tasty, and the pita and hummus was very refreshing.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (75, 67, "We ordered the duck rare and it was pink and tender on the inside with a nice char on the outside.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (42, 58, "He came running after us when he realized my husband had left his sunglasses on the table.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (106, 77, "Their chow mein is so good!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (69, 36, "They have horrible attitudes towards customers, and talk down to each one when customers don't enjoy their food.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (14, 54, "The portion was huge!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (53, 13, "Loved it...friendly servers, great food, wonderful and imaginative menu.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (55, 77, "The Heart Attack Grill in downtown Vegas is an absolutely flat-lined excuse for a restaurant.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (98, 30, "Not much seafood and like 5 strings of pasta at the bottom.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (41, 50, "The salad had just the right amount of sauce to not over power the scallop, which was perfectly cooked.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (133, 72, "The ripped banana was not only ripped, but petrified and tasteless.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (61, 3, "At least think to refill my water before I struggle to wave you over for 10 minutes.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (82, 69, "This place receives stars for their APPETIZERS!!!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (68, 40, "The cocktails are all handmade and delicious.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (57, 89, "We'd definitely go back here again.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (110, 53, "We are so glad we found this place.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (89, 20, "Great food and service, huge portions and they give a military discount.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (109, 37, "Always a great time at Dos Gringos!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (124, 5, "Update.....went back for a second time and it was still just as amazing", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (114, 83, "We got the food and apparently they have never heard of salt and the batter on the fish was chewy.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (51, 91, "A great way to finish a great.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (37, 61, "The deal included 5 tastings and 2 drinks, and Jeff went above and beyond what we expected.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (138, 6, "- Really, really good rice, all the time.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (96, 15, "The service was meh.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (74, 5, "It took over 30 min to get their milkshake, which was nothing more than chocolate milk.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (148, 51, "I guess I should have known that this place would suck, because it is inside of the Excalibur, but I didn't use my common sense.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (31, 55, "The scallop dish is quite appalling for value as well.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (72, 29, "2 times - Very Bad Customer Service !", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (105, 50, "The sweet potato fries were very good and seasoned well.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (37, 42, "Today is the second time I've been to their lunch buffet and it was pretty good.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (102, 46, "There is so much good food in Vegas that I feel cheated for wasting an eating opportunity by going to Rice and Company.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (112, 21, "Coming here is like experiencing an underwhelming relationship where both parties can't wait for the other person to ask to break up.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (130, 55, "walked in and the place smelled like an old grease trap and only 2 others there eating.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (145, 36, "The turkey and roast beef were bland.	", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (16, 10, "This place has it!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (140, 40, "The pan cakes everyone are raving about taste like a sugary disaster tailored to the palate of a six year old.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (41, 55, "I love the Pho and the spring rolls oh so yummy you have to try.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (129, 7, "The poor batter to meat ratio made the chicken tenders very unsatisfying.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (64, 14, "All I have to say is the food was amazing!!!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (62, 71, "Omelets are to die for!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (131, 71, "Everything was fresh and delicious!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (23, 56, "In summary, this was a largely disappointing dining experience.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (44, 24, "It's like a really sexy party in your mouth, where you're outrageously flirting with the hottest person at the party.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (98, 38, "Never been to Hard Rock Casino before, WILL NEVER EVER STEP FORWARD IN IT AGAIN!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (77, 35, "Best breakfast buffet!!!", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (41, 60, "say bye bye to your tip lady!", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (13, 85, "We'll never go again.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (68, 47, "Will be back again!	", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (89, 26, "Food arrived quickly!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (11, 86, "It was not good.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (103, 50, "On the up side, their cafe serves really good food.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (35, 35, "Our server was fantastic and when he found out the wife loves roasted garlic and bone marrow, he added extra to our meal and another marrow to go!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (119, 51, "The only good thing was our waiter, he was very helpful and kept the bloddy mary's coming.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (123, 10, "Best Buffet in town, for the price you cannot beat it.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (106, 48, "I LOVED their mussels cooked in this wine reduction, the duck was tender, and their potato dishes were delicious.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (9, 71, "This is one of the better buffets that I have been to.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (78, 82, "So we went to Tigerlilly and had a fantastic afternoon!", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (95, 19, "The food was delicious, our bartender was attentive and personable AND we got a great deal!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (22, 87, "The ambience is wonderful and there is music playing.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (54, 77, "Will go back next trip out.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (66, 62, "Sooooo good!!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (135, 10, "REAL sushi lovers, let's be honest - Yama is not that good.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (127, 48, "At least 40min passed in between us ordering and the food arriving, and it wasn't that busy.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (132, 16, "This is a really fantastic Thai restaurant which is definitely worth a visit.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (8, 64, "Nice, spicy and tender.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (123, 86, "Good prices.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (87, 35, "Check it out.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (130, 56, "It was pretty gross!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (86, 41, "I've had better atmosphere.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (23, 64, "Kind of hard to mess up a steak but they did.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (78, 60, "Although I very much liked the look and sound of this place, the actual experience was a bit disappointing.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (34, 22, "I just don't know how this place managed to served the blandest food I have ever eaten when they are preparing Indian cuisine.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (25, 47, "Worst service to boot, but that is the least of their worries.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (70, 6, "Service was fine and the waitress was friendly.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (27, 80, "The guys all had steaks, and our steak loving son who has had steak at the best and worst places said it was the best steak he's ever eaten.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (39, 76, "We thought you'd have to venture further away to get good sushi, but this place really hit the spot that night.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (124, 90, "Host staff were, for lack of a better word, BITCHES!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (83, 83, "Bland... Not a liking this place for a number of reasons and I don't want to waste time on bad reviewing.. I'll leave it at that...", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (125, 49, "Phenomenal food, service and ambiance.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (2, 63, "I wouldn't return.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (56, 59, "Definitely worth venturing off the strip for the pork belly, will return next time I'm in Vegas.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (149, 4, "This place is way too overpriced for mediocre food.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (85, 86, "Penne vodka excellent!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (20, 70, "They have a good selection of food including a massive meatloaf sandwich, a crispy chicken wrap, a delish tuna melt and some tasty burgers.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (67, 33, "The management is rude.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (82, 7, "Delicious NYC bagels, good selections of cream cheese, real Lox with capers even.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (114, 26, "Great Subway, in fact it's so good when you come here every other Subway will not meet your expectations.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (120, 22, "I had a seriously solid breakfast here.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (94, 63, "This is one of the best bars with food in Vegas.	", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (44, 74, "He was extremely rude and really, there are so many other restaurants I would love to dine at during a weekend in Vegas.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (4, 54, "My drink was never empty and he made some really great menu suggestions.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (25, 31, "Don't do it!!!!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (75, 29, "The waiter wasn't helpful or friendly and rarely checked on us.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (96, 18, "My husband and I ate lunch here and were very disappointed with the food and service.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (145, 56, "And the red curry had so much bamboo shoots and wasn't very tasty to me.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (5, 90, "Nice blanket of moz over top but i feel like this was done to cover up the subpar food.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (148, 71, "The bathrooms are clean and the place itself is well decorated.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (57, 21, "The menu is always changing, food quality is going down & service is extremely slow.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (150, 80, "The service was a little slow , considering that were served by 3 people servers so the food was coming in a slow pace.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (133, 63, "I give it 2 thumbs down", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (141, 61, "We watched our waiter pay a lot more attention to other tables and ignore us.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (136, 27, "My fianc챕 and I came in the middle of the day and we were greeted and seated right away.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (62, 58, "This is a great restaurant at the Mandalay Bay.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (91, 69, "We waited for forty five minutes in vain.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (140, 67, "Crostini that came with the salad was stale.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (33, 77, "Some highlights : Great quality nigiri here!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (107, 5, "the staff is friendly and the joint is always clean.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (39, 24, "this was a different cut than the piece the other day but still wonderful and tender s well as well flavored.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (123, 82, "I ordered the Voodoo pasta and it was the first time I'd had really excellent pasta since going gluten free several years ago.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (39, 55, "this place is good.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (33, 16, "Unfortunately, we must have hit the bakery on leftover day because everything we ordered was STALE.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (145, 91, "I came back today since they relocated and still not impressed.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (128, 85, "I was seated immediately.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (1, 30, "Their menu is diverse, and reasonably priced.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (81, 53, "Avoid at all cost!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (128, 89, "Restaurant is always full but never a wait.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (14, 2, "DELICIOUS!!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (101, 12, "This place is hands-down one of the best places to eat in the Phoenix metro area.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (3, 39, "So don't go there if you are looking for good food...", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (85, 14, "I've never been treated so bad.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (4, 77, "Bacon is hella salty.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (119, 74, "We also ordered the spinach and avocado salad, the ingredients were sad and the dressing literally had zero taste.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (66, 69, "This really is how Vegas fine dining used to be, right down to the menus handed to the ladies that have no prices listed.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (3, 66, "The waitresses are very friendly.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (87, 61, "Lordy, the Khao Soi is a dish that is not to be missed for curry lovers!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (65, 77, "Everything on the menu is terrific and we were also thrilled that they made amazing accommodations for our vegetarian daughter.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (120, 35, "Perhaps I caught them on an off night judging by the other reviews, but I'm not inspired to go back.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (82, 40, "The atmosphere is modern and hip, while maintaining a touch of coziness.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (8, 52, "Not a weekly haunt, but definitely a place to come back to every once in a while.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (22, 85, "We literally sat there for 20 minutes with no one asking to take our order.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (78, 45, "The burger had absolutely no flavor - the meat itself was totally bland, the burger was overcooked and there was no charcoal flavor.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (78, 18, "I also decided not to send it back because our waitress looked like she was on the verge of having a heart attack.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (2, 81, "I dressed up to be treated so rudely!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (45, 62, "It was probably dirt.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (141, 13, "Love this place, hits the spot when I want something healthy but not lacking in quantity or flavor.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (92, 60, "I ordered the Lemon raspberry ice cocktail which was also incredible.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (94, 72, "The food sucked, which we expected but it sucked more than we could have imagined.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (66, 36, "Interesting decor.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (112, 57, "What I really like there is the crepe station.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (57, 58, "Also were served hot bread and butter, and home made potato chips with bacon bits on top....very original and very good.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (74, 21, "you can watch them preparing the delicious food!)", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (23, 77, "Both of the egg rolls were fantastic.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (136, 14, "When my order arrived, one of the gyros was missing.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (106, 31, "I had a salad with the wings, and some ice cream for dessert and left feeling quite satisfied.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (19, 2, "I'm not really sure how Joey's was voted best hot dog in the Valley by readers of Phoenix Magazine.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (95, 29, "The best place to go for a tasty bowl of Pho!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (29, 76, "The live music on Fridays totally blows.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (143, 20, "I've never been more insulted or felt disrespected.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (76, 13, "Very friendly staff.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (50, 36, "It is worth the drive.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (147, 7, "I had heard good things about this place, but it exceeding every hope I could have dreamed of.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (150, 30, "Food was great and so was the serivce!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (66, 7, "The warm beer didn't help.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (151, 64, "Great brunch spot.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (56, 87, "Service is friendly and inviting.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (85, 9, "Very good lunch spot.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (70, 50, "I've lived here since 1979 and this was the first (and last) time I've stepped foot into this place.	", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (141, 86, "The WORST EXPERIENCE EVER.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (101, 58, "Must have been an off night at this place.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (7, 73, "The sides are delish - mixed mushrooms, yukon gold puree, white corn - beateous.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (119, 89, "If that bug never showed up I would have given a 4 for sure, but on the other side of the wall where this bug was climbing was the kitchen.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (140, 69, "For about 10 minutes, we we're waiting for her salad when we realized that it wasn't coming any time soon.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (90, 24, "My friend loved the salmon tartar.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (8, 15, "Won't go back.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (68, 31, "Extremely Tasty!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (104, 81, "Waitress was good though!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (151, 67, "Soggy and not good.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (66, 2, "The Jamaican mojitos are delicious.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (107, 4, "Which are small and not worth the price.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (117, 81, "- the food is rich so order accordingly.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (56, 9, "The shower area is outside so you can only rinse, not take a full shower, unless you don't mind being nude for everyone to see!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (33, 27, "The service was a bit lacking.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (66, 8, "Lobster Bisque, Bussell Sprouts, Risotto, Filet ALL needed salt and pepper..and of course there is none at the tables.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (29, 62, "Hopefully this bodes for them going out of business and someone who can cook can come in.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (102, 73, "It was either too cold, not enough flavor or just bad.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (1, 52, "I loved the bacon wrapped dates.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (64, 52, "This is an unbelievable BARGAIN!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (81, 70, "The folks at Otto always make us feel so welcome and special.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (133, 45, "This is the place where I first had pho and it was amazing!!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (64, 6, "This wonderful experience made this place a must-stop whenever we are in town again.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (90, 88, "If the food isn't bad enough for you, then enjoy dealing with the world's worst/annoying drunk people.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (119, 84, "Very very fun chef.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (93, 77, "Ordered a double cheeseburger & got a single patty that was falling apart (picture uploaded) Yeah, still sucks.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (17, 43, "Great place to have a couple drinks and watch any and all sporting events as the walls are covered with TV's.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (91, 43, "If it were possible to give them zero stars, they'd have it.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (31, 18, "I'd say that would be the hardest decision... Honestly, all of M's dishes taste how they are supposed to taste (amazing).", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (14, 65, "If she had not rolled the eyes we may have stayed... Not sure if we will go back and try it again.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (11, 53, "Everyone is very attentive, providing excellent customer service.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (99, 45, "Horrible - don't waste your time and money.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (11, 75, "Now this dish was quite flavourful.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (140, 77, "By this time our side of the restaurant was almost empty so there was no excuse.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (18, 80, "(It wasn't busy either) Also, the building was FREEZING cold.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (52, 67, "-Drinks took close to 30 minutes to come out at one point.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (142, 73, "Seriously flavorful delights, folks.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (99, 61, "Much better than the other AYCE sushi place I went to in Vegas.", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (133, 18, "The lighting is just dark enough to set the mood.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (80, 64, "Based on the sub-par service I received and no effort to show their gratitude for my business I won't be going back.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (123, 14, "Owner's are really great people.!", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (69, 70, "There is nothing privileged about working/eating there.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (105, 12, "The Greek dressing was very creamy and flavorful.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (98, 57, "Overall, I don't think that I would take my parents to this place again because they made most of the similar complaints that I silently felt too.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (5, 4, "Now the pizza itself was good the peanut sauce was very tasty.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (30, 56, "We had 7 at our table and the service was pretty fast.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (117, 58, "Fantastic service here.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (95, 64, "I as well would've given godfathers zero stars if possible.	", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (50, 72, "They know how to make them here.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (149, 19, "very tough and very short on flavor!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (93, 73, "I hope this place sticks around.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (142, 27, "I have been in more than a few bars in Vegas, and do not ever recall being charged for tap water.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (132, 1, "The restaurant atmosphere was exquisite.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (97, 39, "Good service, very clean, and inexpensive, to boot!", 1);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (108, 5, "The seafood was fresh and generous in portion.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (21, 19, "Plus, it's only 8 bucks.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (18, 80, "The service was not up to par, either.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (19, 15, "Thus far, have only visited twice and the food was absolutely delicious each time.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (48, 14, "Just as good as when I had it more than a year ago!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (103, 23, "For a self proclaimed coffee cafe, I was wildly disappointed.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (135, 46, "The Veggitarian platter is out of this world!", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (122, 60, "You cant go wrong with any of the food here.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (10, 72, "You can't beat that.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (129, 9, "Stopped by this place while in Madison for the Ironman, very friendly, kind staff.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (116, 69, "Def coming back to bowl next time", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (44, 57, "If you want healthy authentic or ethic food, try this place.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (83, 81, "I will continue to come here on ladies night andddd date night ... highly recommend this place to anyone who is in the area.", 5);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (140, 89, "I have been here several times in the past, and the experience has always been great.", 4);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (100, 67, "We walked away stuffed and happy about our first Vegas buffet experience.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (56, 17, "Service was excellent and prices are pretty reasonable considering this is Vegas and located inside the Crystals shopping mall by Aria.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (110, 41, "To summarize... the food was incredible, nay, transcendant... but nothing brings me joy quite like the memory of the pneumatic condiment dispenser.", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (145, 68, "I'm probably one of the few people to ever go to Ians and not like it.", 3);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (17, 47, "Kids pizza is always a hit too with lots of great side dish options for the kiddos!", 2);
INSERT INTO review (user_id, rest_id, content, rating) VALUES (55, 40, "Service is perfect and the family atmosphere is nice to see.", 2);